import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import imageLoader from "../imageLoader";
import styles from "../styles/Home.module.css";
import path from 'path';
import { promises as fs } from 'fs';
import { Character, GetCharacterResults,Employee,GetEmployeeResults } from "../types";

const Home: NextPage<{ characters: Employee[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {characters.map((character) => {
        return (
          <div key={character.id}>
            <Link href={`/characters/${character.id}`}>
              <a>
                <h3>{character.first_name}</h3>
              </a>
            </Link>


          </div>
        );
      })}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  // const res = await fetch("https://rickandmortyapi.com/api/character");
  const filePath = path.join(process.cwd(), 'employees.json');
  const jsonData = await fs.readFile(filePath,'utf-8');
  const results:GetEmployeeResults = JSON.parse(jsonData)

  return {
    props: {
      characters: results,
    },
  };
};

export default Home;
